service: test-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  stage: 
  region: ap-south-1

functions:
  app:
    handler: src/lamda.handler
    events:
      - http:
          path: /
          method: ANY
    timeout: 10
plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
